#!/bin/sh

# $#: This special variable holds the number of command-line arguments passed to the script.
# [ $# -gt 0 ]: This condition checks if the number of arguments is greater than 0.

if [ $# -gt 0 ]; then
    if [ "$1" == "--lower-off" ] || [ $1 == "-lo" ]; then
        string=${*:2}
    else
        string=$(echo $@ | tr '[:upper:]' '[:lower:]')
    fi

elif [[ -t 0 ]]; then  # Check if stdin is a terminal (not a pipe)
    echo "Usage:\n  dashfy <string>\n"
    echo "Options:\n -lo, --lower-off          Avoid lowercasing text"
    exit 1
else
    string=$(cat -)
fi

echo $string | tr ' ' '-' | tr '_' '-'
